### ISSUE TITLE
Linting does not fail if conda package dependency misses version tag

### ISSUE THREAD

**Issue by sven1103** [qbicsoftware/rmageddon-cli#8]
**Observed behaviour**
With the current release `0.1.0`, the linting passes even if conda package dependencies have no pinned version number.

**Expected behaviour**
rmageddon should display a linting error with the name of the package missing a version tag.

**Comment by Zethson** [comment]
@sven1103 
Could you please provide me with an example that passes, but actually shouldn't?
Then I can get this done quickly.

If I understood correctly, all dependencies (or only those from bioconda?) should have their version number pinned right?
So this [QSCRN](https://github.com/qbicsoftware/r-container-lib/blob/master/projects/QSCRN/environment.yml) should not pass the linting, since not all dependency versions are pinned down?

**Comment by Zethson** [comment]
@sven1103 The current release is [0.2.1 in pipy](https://pypi.org/project/rmageddon/) by the way.
I'll make this more clear in the README and also the github releases page.

**Comment by Zethson** [comment]
Addressed by https://github.com/qbicsoftware/rmageddon-cli/pull/10
